# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-02 03:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u4f5c\u8005\u540d')),
                ('write_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u5199\u4f5c\u5e74\u9f84')),
                ('introduce', models.CharField(blank=True, max_length=300, null=True, verbose_name='\u81ea\u6211\u4ecb\u7ecd')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='\u6536\u85cf\u6570')),
                ('click_nums', models.IntegerField(default=0, verbose_name='\u6d4f\u89c8\u91cf')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u4f5c\u8005',
                'verbose_name_plural': '\u4f5c\u8005',
            },
        ),
    ]
