# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-05 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(default='', upload_to='author/%Y/%m', verbose_name='\u5934\u50cf'),
        ),
    ]
