# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-14 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20171013_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='birday',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='mobile',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='introduce',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='\u81ea\u6211\u4ecb\u7ecd'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.CharField(default='http://oxr5eyw7q.bkt.clouddn.com/75fc0f9cb00211e7bb4b000c299be46c.jpg', max_length=200, verbose_name='\u7528\u6237\u5934\u50cf\u7684\u4e03\u725b\u4e91\u5730\u5740'),
        ),
    ]
