# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-14 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20171013_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.CharField(default='http://oxr5eyw7q.bkt.clouddn.com/85efe984b00511e7bb4b000c299be46c.jpg', max_length=200, verbose_name='\u6587\u7ae0\u5c01\u9762\u56fe\u7684\u4e03\u725b\u4e91\u5730\u5740'),
        ),
    ]
